# Generated by Django 5.2.6 on 2025-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='friend',
            name='api_friend_sender__dfedbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='friend',
            name='api_friend_receive_6d4219_idx',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friend',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['sender_id', 'status'], name='api_friend_sender__dfedbd_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['receiver_id', 'status'], name='api_friend_receive_6d4219_idx'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('sender_id', 'receiver_id'), name='unique_sender_receiver'),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sender',
        ),
    ]
