# Generated by Django 5.2.6 on 2025-10-01 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_friend_api_friend_sender__dfedbd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_sender_receiver',
        ),
        migrations.RemoveIndex(
            model_name='friend',
            name='api_friend_sender__dfedbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='friend',
            name='api_friend_receive_6d4219_idx',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='friend',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['sender', 'status'], name='api_friend_sender__dfedbd_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['receiver', 'status'], name='api_friend_receive_6d4219_idx'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_sender_receiver'),
        ),
    ]
