version: "3.8"

services:
  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    environment: 
      - SERVER_NAME=${SERVER_NAME}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - CERT_NAME=${CERT_NAME}
    depends_on:
      - backend

  backend:
    image: ${REGISTRY_URL}/${REGISTRY}/${DOCKER_IMAGE}:latest
    container_name: ${CONTAINER_NAME}
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application

networks:
  default:
    driver: bridge