# Framework-generated: 0%
# Human-written: 100%
# AI-generated: 0% (cors origins)

version: "3.8"

services:
  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    environment: 
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - frontend

  frontend:
    image: ${REGISTRY_URL}/${REGISTRY}/${DOCKER_IMAGE}:latest
    container_name: ${CONTAINER_NAME}
    env_file:
      - ./.env
    ports:
      - "80:80"

networks:
  default:
    driver: bridge