name: Backend Dev CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: development
    
    defaults:
      run:
        working-directory: backend
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file from environment variables
      run: |
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
        echo "MONGO_DATABASE_HOST=${{ secrets.MONGO_DATABASE_HOST }}" >> .env
        echo "MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }}" >> .env
        echo "MONGO_DATABASE_USER=${{ secrets.MONGO_DATABASE_USER }}" >> .env
        echo "MONGO_DATABASE_PWD=${{ secrets.MONGO_DATABASE_PWD }}" >> .env
        echo "MONGO_DATABASE_PORT=${{ secrets.MONGO_DATABASE_PORT }}" >> .env
        echo "MONGO_DATABASE_TLS=${{ secrets.MONGO_DATABASE_TLS }}" >> .env
        echo "MONGO_DATABASE_SSL=${{ secrets.MONGO_DATABASE_SSL }}" >> .env
    - name: Run Tests
      run: |
        python manage.py test
    - name: Trigger Render Deploy Hook
      run: curl -X POST ${{ secrets.RENDER_BACKEND_DEV_DEPLOY_URL }}
